import { Router } from "express";

import { dashboard } from "../controllers/analytics-controller.js";
import { login } from "../controllers/auth-controller.js";
import { changeOwnership, createCustomer, createStore, deleteCustomer, exportRegionalCustomers, getCustomer, importCustomers, listCustomers, listDealerGroups, listStores, updateCustomer } from "../controllers/customer-controller.js";
import { createOrder, createPayment, getOrder, listOrders } from "../controllers/order-controller.js";
import { createTask, listTasks, updateTask } from "../controllers/task-controller.js";
import { changeMyAvatar, changeMyPassword, createUser, deleteUser, getMe, listOrganizations, listUsers, updateUser } from "../controllers/user-controller.js";
import { authenticate } from "../middleware/auth.js";
import { requireAdmin } from "../middleware/authorization.js";

export const apiRouter = Router();

apiRouter.post("/auth/login", login);
apiRouter.use(authenticate);
apiRouter.get("/auth/me", getMe);
apiRouter.patch("/auth/me/password", changeMyPassword);
apiRouter.patch("/auth/me/avatar", changeMyAvatar);
apiRouter.use("/users", requireAdmin);
apiRouter.get("/users", listUsers);
apiRouter.post("/users", createUser);
apiRouter.patch("/users/:id", updateUser);
apiRouter.delete("/users/:id", deleteUser);
apiRouter.get("/organizations", listOrganizations);
apiRouter.get("/customers", listCustomers);
apiRouter.post("/customers", createCustomer);
apiRouter.post("/customers/import", importCustomers);
apiRouter.get("/customers/export-regional", exportRegionalCustomers);
apiRouter.get("/customers/:id", getCustomer);
apiRouter.patch("/customers/:id", updateCustomer);
apiRouter.delete("/customers/:id", deleteCustomer);
apiRouter.patch("/customers/:id/ownership", changeOwnership);
apiRouter.get("/stores", listStores);
apiRouter.post("/stores", createStore);
apiRouter.get("/dealer-groups", listDealerGroups);
apiRouter.get("/orders", listOrders);
apiRouter.post("/orders", createOrder);
apiRouter.get("/orders/:id", getOrder);
apiRouter.post("/orders/:id/payments", createPayment);
apiRouter.get("/tasks", listTasks);
apiRouter.post("/tasks", createTask);
apiRouter.patch("/tasks/:id", updateTask);
apiRouter.get("/analytics/dashboard", dashboard);
