import { Router } from "express";

import { dashboard } from "../controllers/analytics-controller.js";
import { login } from "../controllers/auth-controller.js";
import { batchDeleteCustomers, batchUpdateCustomers, changeOwnership, createCustomer, createStore, deleteCustomer, exportRegionalCustomers, getCustomer, importCustomers, listCustomers, listDealerGroups, listStores, updateCustomer } from "../controllers/customer-controller.js";
import { createOrder, createPayment, getOrder, listOrders } from "../controllers/order-controller.js";
import { createTask, listTasks, updateTask } from "../controllers/task-controller.js";
import { createRole, deleteRole, listRoles, updateRole } from "../controllers/role-controller.js";
import { changeMyAvatar, changeMyPassword, createPosition, createUser, deleteUser, getMe, listOrganizations, listPositions, listUsers, updateUser } from "../controllers/user-controller.js";
import { authenticate } from "../middleware/auth.js";
import { requireAdmin, requirePermission } from "../middleware/authorization.js";

export const apiRouter = Router();

apiRouter.post("/auth/login", login);
apiRouter.use(authenticate);
apiRouter.get("/auth/me", getMe);
apiRouter.patch("/auth/me/password", changeMyPassword);
apiRouter.patch("/auth/me/avatar", changeMyAvatar);
apiRouter.use("/users", requireAdmin);
apiRouter.get("/users", listUsers);
apiRouter.post("/users", createUser);
apiRouter.patch("/users/:id", updateUser);
apiRouter.delete("/users/:id", deleteUser);
apiRouter.use("/positions", requireAdmin);
apiRouter.get("/positions", listPositions);
apiRouter.post("/positions", createPosition);
apiRouter.use("/roles", requirePermission("role.read"));
apiRouter.get("/roles", listRoles);
apiRouter.post("/roles", requirePermission("role.manage"), createRole);
apiRouter.patch("/roles/:id", requirePermission("role.manage"), updateRole);
apiRouter.delete("/roles/:id", requirePermission("role.manage"), deleteRole);
apiRouter.get("/organizations", requirePermission("organization.read"), listOrganizations);
apiRouter.get("/customers", requirePermission("customer.read"), listCustomers);
apiRouter.post("/customers", requirePermission("customer.create"), createCustomer);
apiRouter.post("/customers/import", requirePermission("customer.create"), importCustomers);
apiRouter.get("/customers/export-regional", requirePermission("customer.export"), exportRegionalCustomers);
apiRouter.patch("/customers/batch", requirePermission("customer.update"), batchUpdateCustomers);
apiRouter.post("/customers/batch-delete", requirePermission("customer.delete"), batchDeleteCustomers);
apiRouter.get("/customers/:id", requirePermission("customer.read"), getCustomer);
apiRouter.patch("/customers/:id", requirePermission("customer.update"), updateCustomer);
apiRouter.delete("/customers/:id", requirePermission("customer.delete"), deleteCustomer);
apiRouter.patch("/customers/:id/ownership", requirePermission("customer.transfer"), changeOwnership);
apiRouter.get("/stores", requirePermission("organization.read"), listStores);
apiRouter.post("/stores", requirePermission("organization.manage"), createStore);
apiRouter.get("/dealer-groups", requirePermission("organization.read"), listDealerGroups);
apiRouter.get("/orders", requirePermission("order.read"), listOrders);
apiRouter.post("/orders", requirePermission("order.manage"), createOrder);
apiRouter.get("/orders/:id", requirePermission("order.read"), getOrder);
apiRouter.post("/orders/:id/payments", requirePermission("payment.manage"), createPayment);
apiRouter.get("/tasks", requirePermission("task.read"), listTasks);
apiRouter.post("/tasks", requirePermission("task.manage"), createTask);
apiRouter.patch("/tasks/:id", requirePermission("task.manage"), updateTask);
apiRouter.get("/analytics/dashboard", requirePermission("analytics.read"), dashboard);
